### ISSUE TITLE
Does TiBigData support lookup join?

### ISSUE THREAD

**Issue by gbzy** [tidb-incubator/TiBigData#111]

**Comment by gbzy** [comment]
> If you meant Lookup Table Source in Flink, yes it is supported.

Thanks. Does  LookupTableSource support async mode?

**Comment by sunxiaoguang** [comment]
Since TiBigData `Lookup Table Source` implementation is a simple wrapper of `JDBC Lookup Table Source` at this time. Therefore it depends on JDBC connector in Flink. To my understanding, JDBC lookup table source does not support async mode in `master` branch.
