### ISSUE TITLE
Read region error 

### ISSUE THREAD

**Issue by gbzy** [tidb-incubator/TiBigData#113]
![9480E254-C4DE-42c3-AABE-60EAD3C2B5F7-01](https://user-images.githubusercontent.com/18411217/139244724-d87642eb-f7ed-4827-99a8-8accf9f10d89.jpeg)

**Comment by sunxiaoguang** [comment]
@humengyu2012 Can you take a look when you are convenient after rushing hacking camp?

**Comment by humengyu2012** [comment]
Can you provide more information? It appears to be just a warning and not an error. Did the flink job finally run successfully?

**Comment by sunxiaoguang** [comment]
> Can you provide more information? It appears to be just a warning and not an error. Did the flink job finally run successfully?

@gbzy could you please tell us more about the issue? As it is stated previously.

**Comment by gbzy** [comment]
> > Can you provide more information? It appears to be just a warning and not an error. Did the flink job finally run successfully?
> 
> @gbzy could you please tell us more about the issue? As it is stated previously.

This warnings appears in task manager logs when the number of task manager core is set to 1 and the number of slot is set to 1, which finally cause the task to fail, it disappears when I increase the number of core to 2.
