### ISSUE TITLE
presto delete tidb table error

### ISSUE THREAD

**Issue by wjf989** [tidb-incubator/TiBigData#14]
![image](https://user-images.githubusercontent.com/49484750/91156158-5cb60f00-e6f6-11ea-96d0-07ad6ba55131.png)
when can use delete function？？？

**Comment by humengyu2012** [comment]
It will be supported soon, I'm working for upsert and delete

**Comment by wjf989** [comment]
very good！thanks

**Comment by humengyu2012** [comment]
thanks for your issue, I found that presto will scan data before delete opration, that means, deleting tidb data by presto is inefficient. It would be better to use sql-client(such as mysql client) than presto.
