### ISSUE TITLE
JDBC Connector URL Parse returns exception

### ISSUE THREAD

**Issue by WilliamShine** [tidb-incubator/TiBigData#141]
I use flink tidb connector for put the CDC data in kafka to Tidb,But some exception happend,if i use jdbc:mysql://ip1,ip2,ip3:4000/database1 to connect,flink job has fail,and error log is 
java.sql.SQLSyntaxErrorException: function READ ONLY has only noop implementation in tidb now, use tidb_enable_noop_functions to enable these functions.
but when i use this url :jdbc:mysql://ip1:4000,ip2:4000,ip3:4000/database1,flink job is run,Why does this happen？if my url is wrong,why return read only error log?

**Comment by WilliamShine** [comment]
CREATE TABLE if not exists `kafkaCdcTable`(
) WITH (
'connector'='kafka',
'format'='debezium-avro-confluent'
);

CREATE TABLE if not exists `tidbTable`(
 PRIMARY KEY (`id`) NOT ENFORCED 
) WITH (
'connector'='tidb',
'tidb.database.url'='jdbc:mysql://ip1,ip2,ip3:4000/database1',
'tidb.username'='',
'tidb.password'='',
'tidb.database.name'='database1',
'tidb.table.name'='table1',
'tidb.maximum.pool.size'='1',
'tidb.minimum.idle.size'='1',
'tidb.write_mode'='upsert',
'sink.buffer-flush.max-rows'='0');

insert into `tidbTable` from `kafkaCdcTable`;


jdbc:mysql://ip1,ip2,ip3:4000/database1                 #read only error
jdbc:mysql://ip1:4000,ip2:4000,ip3:4000/database1       #succes

**Comment by xuanyu66** [comment]
@sunxiaoguang @humengyu2012 PTAL

**Comment by humengyu2012** [comment]
You could just write as
```sql
CREATE TABLE if not exists tidbTable(
PRIMARY KEY (id) NOT ENFORCED
) WITH (
'connector'='tidb',
'tidb.database.url'='jdbc:tidb://ip1:4000/database1',
'tidb.username'='',
'tidb.password'='',
'tidb.database.name'='database1',
'tidb.table.name'='table1',
'tidb.maximum.pool.size'='1',
'tidb.minimum.idle.size'='1',
'tidb.write_mode'='upsert',
'sink.buffer-flush.max-rows'='0');
```sql
If you have multiple TiDB server addresses and the amount of data to be inserted is huge, it would be better to use TiDB jdbc driver rather then MySQL jdbc driver. TiDB driver is a load-balancing driver, it will query all TiDB server addresses and pick one randomly when establishing connections.
TiDB sink implemented by jdbc sink, so update and delete row are not supported.

**Comment by humengyu2012** [comment]
The table api will not be supported in tidb-flink-connector-1.14, you could use catalog like:
```sql
CREATE catalog `tidb_catalog`(
PRIMARY KEY (id) NOT ENFORCED
) WITH (
'type'='tidb',
'tidb.database.url'='jdbc:tidb://ip1:4000/database1',
'tidb.username'='',
'tidb.password'='',
'tidb.maximum.pool.size'='1',
'tidb.minimum.idle.size'='1',
'tidb.write_mode'='upsert',
'sink.buffer-flush.max-rows'='0');
```sql

**Comment by WilliamShine** [comment]
ok,thanks for you reply,catalog is better to use,and where is TiDB driver cold and jar can download?

**Comment by humengyu2012** [comment]
TiDB driver is implemented in module `jdbc`, which is included by flink-connector, just use it!

**Comment by WilliamShine** [comment]
ok,thanks,if suggest use tidb drive and is stability,can update README.md  Demo  for other people.Thanks~
