### ISSUE TITLE
support flink1.13？

### ISSUE THREAD

**Issue by TheEros** [tidb-incubator/TiBigData#76]

**Comment by humengyu2012** [comment]
Yes, we are looking into flink-1.13, and support it soon.

**Comment by sunxiaoguang** [comment]
In case people waste their effort to work on Flink 1.13 support. I would like to introduce little bit about our current progress on 1.13 support. 

Acutally it is not just about 1.13 support, the whole implementation is been rewritten again to use new connector system which makes it possible to implement unified batch and streaming connector that support parallelism which is critical for processing large data set, which apparently is typical case for TiDB. 

We will create pull request ASAP so people can know what's the current status and leave comments about it. Thanks.

**Comment by sunxiaoguang** [comment]
The work in progress PR is created: #86

**Comment by sunxiaoguang** [comment]
Flink 1.13 support was merged and couple of issues found during test was addressed. @humengyu2012 will run canary test in production environment in the coming weeks. Will keep everybody posed here, cheers.

**Comment by sunxiaoguang** [comment]
After couple months' evaluation in production, we believe Flink 1.13 support is stable enough for batch workload.
