### ISSUE TITLE
Use sql-client in Flink-1.13 get exception

### ISSUE THREAD

**Issue by humengyu2012** [tidb-incubator/TiBigData#90]
![image](https://user-images.githubusercontent.com/45056332/126134856-1f05db3b-f361-40a8-9723-1e3e403c3565.png)
![image](https://user-images.githubusercontent.com/45056332/126135008-33c35006-8a7b-44a8-b13d-28dba4b9142a.png)

**Comment by Al-assad** [comment]
It looks like flink-1.13 was modified the catalog spi service  to org.apache.flink.table.factories.Factory

**Comment by humengyu2012** [comment]
https://github.com/tidb-incubator/TiBigData/pull/91/files
